FORMAT: 1A

# adibioshop

adibioshop is a wechat shop for adibio.

# 获取购物车页面 [/shopping_cart]

## GET

+ Response 200 (text/html)

    + Body
            直接获取购物车页面，没有json数据
            
# 获取购物车各项基础信息 [/show_cart_info]

## GET

+ Response 200 (application/json)

    + Body

            {
                "result": "ok",
                "errMsg": "",
                "parm": [
                    {
                        "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                        "cart_itemid": "123",
                        "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                        "product_name": "糖尿病早期筛查",
                        "unit_price": 0.01,
                        "quantity": 123
                    },
                    {
                        "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                        "cart_itemid": "432",
                        "product_id": "83f7c071-7858-4e3f-b000-3c011db15e41",
                        "product_name": "肾病早期筛查",
                        "unit_price": 0.02,
                        "quantity": 432
                    },
                    {
                        "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                        "cart_itemid": "234",
                        "product_id": "27e21552-3127-4b9d-8c79-6c791a22b3ec",
                        "product_name": "中风早期筛查",
                        "unit_price": 0.03,
                        "quantity": 234
                    }
                ]
            }

# 加入购物车 [/add_cart]

## POST
请求参数中，cartItem里的product_id为必填参数，patientInfo的patient_infoid或name,gender,age,province,city,district,address,phone,has_diabetic,is_pregnant二组之一必填
使用ajax发送请求参数，必须对ajax填入contentType: "application/json", 需要将json对象使用JSON.stringify转换
+ Request (application/json)

    + Body

            {
                "cartItem": {
                    "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                    "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                    "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                    "quantity": 1
                },
                "patientInfo": {
                    "customer_id": "60df649c-51c8-4d1d-b02c-47d44d4b7355",
                    "patient_infoid": "41fad720-638d-413c-aa02-dcd2fb3ec573",
                    "name": "张三",
                    "gender": "M",
                    "age": 20.0,
                    "country": "CHINA",
                    "province": "广东省",
                    "city": "深圳市",
                    "district": "南山区",
                    "address": "深圳大学",
                    "phone": "13829610228",
                    "has_diabetic": 0,
                    "is_pregnant": 0,
                    "height": 0.0,
                    "weight": 0.0
                }
            }

+ Response 200 (application/json)

    + Body 正确参数
            
            {
                "result": "ok",
                "errMsg": "",
                "parm": {
                    "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                    "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                    "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                    "quantity": 1
                }
            }
    + Body 错误参数

            {
                "result": "err",
                "errMsg": "can't find the cartItem"
            }

# 减少购物车项目 [/reduce_cart_item]

## POST
+ Request (application/json)

    + Body

            {
                "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                "quantity": 1
            }

+ Response 200 (application/json)

    + Body
            {
                "result": "ok",
                "errMsg": "",
                "parm": {
                    "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                    "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                    "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365/",
                    "quantity": 3
                }
            }

# 查询购物车项目对应的患者信息

## POST

+ Request (application/json)
    + Body

            {
                "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                "quantity": 2
            }

+ Response 200 (application/json)

    + Body
            {
                "result": "ok",
                "errMsg": "",
                "parm": [
                    {
                        "is_pregnant": 0,
                        "has_diabetic": 0,
                        "country": "CHINA",
                        "address": "你好",
                        "gender": "M",
                        "city": "北京市",
                        "weight": 0,
                        "cart_patient_infoid": "899fa698-62c6-40ed-bf92-be97fd60ff99",
                        "province": "北京",
                        "phone": "13000000000",
                        "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                        "district": "东城区",
                        "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                        "name": "李四",
                        "patient_infoid": "9e62c589-cc2e-485c-bae0-a52e9fcfebeb",
                        "age": 20,
                        "height": 0
                    },
                    {
                        "is_pregnant": 0,
                        "has_diabetic": 0,
                        "country": "CHINA",
                        "address": "深圳大学",
                        "gender": "M",
                        "city": "深圳市",
                        "weight": 0,
                        "cart_patient_infoid": "a242f238-ee15-414a-9856-28b4acb25e24",
                        "province": "广东省",
                        "phone": "13000000000",
                        "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365/",
                        "district": "南山区",
                        "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                        "name": "张三",
                        "patient_infoid": "dfdb7bd8-efea-4c0a-8877-3a41a8e93529",
                        "age": 20,
                        "height": 0
                    }
                ]
            }

# 购买购物车选中的商品 [/buy_cart_selects]

## POST 

+ Request (application/json)

    + Body
            [
                {
                    "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                    "cart_itemid": "68e5c479-43cc-4cd4-b67a-2094481e8e6d",
                    "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365/",
                    "quantity": 1
                }, {
                    "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                    "cart_itemid": "432",
                    "product_id": "83f7c071-7858-4e3f-b000-3c011db15e41",
                    "quantity": 1
                }, {
                    "cart_id": "8b077e8d-2881-47fa-90dc-210f273afeaa",
                    "cart_itemid": "234",
                    "product_id": "27e21552-3127-4b9d-8c79-6c791a22b3ec",
                    "quantity": 1
                }
            ]

+ Response 200 (application/json)

    + Body

            {
                "result": "ok",
                "errMsg": "",
                "parm": [
                    {
                        "appId":"1111",
                        "timeStamp":"2222",
                        "nonceStr":"3333",
                        "package_sign_cut":"4444",
                        "signType":"5555",
                        "paySign":"6666"
                    }
                ]
            }
