FORMAT: 1A

# Orders Api

The orders api of adibioshop.

# 查询初始化订单 [/user_init_orders]

## GET

+ Request (text/html)

    + Body
            
            type = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)

+ Response 200 (text/html)

    + Body

            {

            }