FORMAT: 1A

# Orders Api

The orders api of adibioshop.

# 查询初始化订单 [/user_init_orders]

## GET

+ Request (text/html)

    + Body
            
            type = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)

+ Response 200 (application/json)

    + Body

            {
                "result": "ok",
                "errMsg": "",
                "parm": [
                    {
                        "row_id": 16,
                        "customer_id": "3f7d4403-4832-4e17-ab1c-51a0ee85d526",
                        "order_id": "359820142969880576",
                        "price": 0.04,
                        "status": "PAID",
                        "create_time": "Sep 19, 2017 9:56:47 PM",
                        "orderPreviewList": [
                            {
                                "order_itemid": "78274617-73f4-4277-8b00-4669e3aada1c",
                                "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                                "quantity": 2,
                                "product_name": "糖尿病早期筛查"
                            }
                        ]
                    },
                    {
                        "row_id": 7,
                        "customer_id": "3f7d4403-4832-4e17-ab1c-51a0ee85d526",
                        "order_id": "359811431228506112",
                        "price": 0.02,
                        "status": "CREATION",
                        "create_time": "Sep 19, 2017 9:22:10 PM",
                        "orderPreviewList": [
                            {
                                "order_itemid": "a8d9cd31-c512-4518-bf2d-dfc1102dfbc5",
                                "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                                "quantity": 1,
                                "product_name": "糖尿病早期筛查"
                            }
                        ]
                    }
                ]
            }

# 加载部分订单 [/load_more_orders]

## GET

+ Request (text/html)

    + Body

            type = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)
            row_id = 10

+ Response 200 (application/json)

    + Body

            {
                "result": "ok",
                "errMsg": "",
                "parm": [
                    {
                        "row_id": 16,
                        "customer_id": "3f7d4403-4832-4e17-ab1c-51a0ee85d526",
                        "order_id": "359820142969880576",
                        "price": 0.04,
                        "status": "PAID",
                        "create_time": "Sep 19, 2017 9:56:47 PM",
                        "orderPreviewList": [
                            {
                                "order_itemid": "78274617-73f4-4277-8b00-4669e3aada1c",
                                "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                                "quantity": 2,
                                "product_name": "糖尿病早期筛查"
                            }
                        ]
                    },
                    {
                        "row_id": 7,
                        "customer_id": "3f7d4403-4832-4e17-ab1c-51a0ee85d526",
                        "order_id": "359811431228506112",
                        "price": 0.02,
                        "status": "CREATION",
                        "create_time": "Sep 19, 2017 9:22:10 PM",
                        "orderPreviewList": [
                            {
                                "order_itemid": "a8d9cd31-c512-4518-bf2d-dfc1102dfbc5",
                                "product_id": "bda342a2-27c0-4cb1-bed3-11a786391365",
                                "quantity": 1,
                                "product_name": "糖尿病早期筛查"
                            }
                        ]
                    }
                ]
            }



